apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
spec:
  services:
    - name: "web" ## The name of the service you want to export
      consumers:
      - peer: dc2-default ## The name of the peer that receives the service
